// Vercel Routing Middleware: content negotiation for AI agents.
// A request with `Accept: text/markdown` gets the page's markdown mirror
// (generated by scripts/postbuild.mjs) instead of HTML. All other requests
// pass straight through to the static site.
import { rewrite, next } from '@vercel/functions'

export const config = {
  // pages only: skip assets and anything with a file extension
  matcher: ['/', '/((?!assets/|.*\\.[A-Za-z0-9]+$).*)'],
}

const SECTION_INDEX = new Set(['/compare', '/concepts', '/industries'])

export default function middleware(request) {
  const accept = request.headers.get('accept') || ''
  if (!accept.includes('text/markdown')) return next()
  const url = new URL(request.url)
  let path = url.pathname.replace(/\/+$/, '')
  if (path === '') path = '/index'
  else if (SECTION_INDEX.has(path)) path += '/index'
  url.pathname = `${path}.md`
  return rewrite(url)
}
