// Vercel Routing Middleware (vercel.json proxy.entrypoint): content negotiation
// for AI agents. Scoped by proxy.matcher in vercel.json.
// A request with `Accept: text/markdown` gets the page's markdown mirror
// (generated by scripts/postbuild.mjs) instead of HTML. All other requests
// pass straight through to the static site.
import { rewrite, next } from '@vercel/functions'

const SECTION_INDEX = new Set(['/compare', '/concepts', '/industries'])

export default function proxy(request) {
  const accept = request.headers.get('accept') || ''
  if (!accept.includes('text/markdown')) return next()
  const url = new URL(request.url)
  let path = url.pathname.replace(/\/+$/, '')
  if (path === '') path = '/index'
  else if (SECTION_INDEX.has(path)) path += '/index'
  url.pathname = `${path}.md`
  return rewrite(url)
}
